
services:

#-----------------------------------------
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
#    networks:
#      - odoo-network


#----exporter-below

  postgres-exporter:
    container_name: postgres-exporter
    image: bitnami/postgres-exporter:latest
    environment:
      #for specefic db  "postgresql://USER_NAME:USER_PW@IP_ADDRESS:PORT/DB_NAME?sslmode>
      DATA_SOURCE_NAME: "postgresql://odoo:odoo@db:5432/postgres?sslmode=disable"
      POSTGRES_EXPORTER_WEB_LISTEN_ADDRESS: 0.0.0.0:9187
    ports:
      - "9187:9187"
    depends_on:
      db:
        condition: service_started
#      prometehus:
#        condition: service_started
    restart: unless-stopped



#--------------------------------------------
#-----------Monitoring-----------------
#---------AlertManager---
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    volumes:
      #- ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
#    networks:
#      - odoo-network
    restart: unless-stopped

volumes:
  db-data:
#networks:
#  odoo-network:
#    driver: bridge
